### ISSUE TITLE
How could I get the t-SNE visualization like fig.11. in this paper

### ISSUE THREAD

**Issue by Rayoll** [mzhang367/DCDH-PyTorch#1]
I haven't found related visualization codes in this repo,  could you please tell me how to visualize the output of a trained hashing model ?

**Comment by mzhang367** [comment]
A simple way as illustrated in the paper is using t-SNE to visualize the high-dimensional hashing outputs of the trained models. You can directly use t-SNE in scikit-learn, which can be found [here](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html).
