### ISSUE TITLE
The download link of model has expired.

### ISSUE THREAD

**Issue by sawar1n** [mzhang367/DCDH-PyTorch#2]
May I ask if it is possible to update the link.

**Comment by mzhang367** [comment]
Please use the updated link to download: https://drive.google.com/file/d/1OLtVgQQ59alSAsyQdqWZe0t_KiNbSUMm/view?usp=sharing

**Comment by niloofarAzari** [comment]
> Please use the updated link to download: https://drive.google.com/file/d/1OLtVgQQ59alSAsyQdqWZe0t_KiNbSUMm/view?usp=sharing 
It seems that you have not shared the right link. This is the link to the vgg_face subset. Could you please share the link to the pre-trained models?
