### ISSUE TITLE
request for the trained models

### ISSUE THREAD

**Issue by niloofarAzari** [mzhang367/DCDH-PyTorch#3]
Hi, thank you for sharing your great work.
It seems that the link to the trained models is expired. could you please share the trained models again?
Thank you in advance.

P.S. The new link you shared in the issues section is not correct. It is the link to the vgg_face subset.

**Comment by mzhang367** [comment]
Hi, the link of the trained model checkpoints has been updated. Please consider staring our project if you find it useful to your research. Thanks.
